# processPriority is an enum on windows and numeric on unix
#	IDLE_PRIORITY_CLASS
#	BELOW_NORMAL_PRIORITY_CLASS
# 	NORMAL_PRIORITY_CLASS
#	ABOVE_NORMAL_PRIORITY_CLASS
#	HIGH_PRIORITY_CLASS
#	REALTIME_PRIORITY_CLASS
#
#  threadPriority is an enum on windows and numeric on unix
#	THREAD_PRIORITY_ABOVE_NORMAL
#	THREAD_PRIORITY_BELOW_NORMAL
#	THREAD_PRIORITY_HIGHEST
#	THREAD_PRIORITY_IDLE
#	THREAD_PRIORITY_LOWEST
#	THREAD_PRIORITY_NORMAL
#	THREAD_PRIORITY_TIME_CRITICAL
- process: TestProcess
  configVersion: 0.1
  priority: HIGH_PRIORITY_CLASS
---
- thread: 0
  priority: THREAD_PRIORITY_HIGHEST
  stageGroups: [Group1, Group2]
- thread: 1
  priority: THREAD_PRIORITY_NORMAL
  stageGroups: [Group3]
---
- stage: Stage1
  stageGroup: Group1
  stagePriority: 0
  batchCount: 100
  emptyRetryCount: 10
- stage: Stage2
  stageGroup: Group2
  stagePriority: 1
  batchCount: 150
  emptyRetryCount: 15